pipeline{
      agent any
      
      stages{
          stage('Check stage'){
             steps{
                 withMaven(maven: 'Maven')
                    bat 'Maven --version'
              }         
         }
          stage('Compile stage'){
             steps{
                 withMaven(maven: 'Maven')
                    bat 'Maven clean compile'
              }
         }  
          stage('Test stage'){
            steps{
                 withMaven(maven: 'Maven') 
                    bat 'Maven test'
              }
              
         }  
    }
}
