pipeline{
      agent any
      
      stages{
          stage('Check stage'){
             steps{
                   withMaven(maven: 'Maven'){
                       bat 'Maven --version'
                   }
              }         
         }
          stage('Compile stage'){
             steps{
                   withMaven(maven: 'Maven'){
                       bat 'Maven -f mvn-bank/pom.xml compile'
                   }
              }
         }  
          stage('Test stage'){
            steps{
                  withMaven(maven: 'Maven') {
                        bat 'Maven -f mvn-bank/pom.xml install'
                  }
              }
              
         }  
    }
}
